INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('1','Nicolas','Vera','nicolas@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('2','Rosamel','Fierro','generico1@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('3','Generico1','Fierro1','generico2@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('4','Generico2','Fierro2','generico3@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('5','Generico3','Fierro3','generico4@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('6','Generico4','Fierro4','generico5@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('7','Generico5','Fierro5','generico6@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('8','Generico6','Fierro6','generico7@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('9','Generico7','Fierro7','generico8@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('10','Generico8','Fierro8','generico9@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('11','Generico9','Fierro9','generico10@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('12','Generico10','Fierro10','generico11@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('13','Generico11','Fierro11','generico12@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('14','Generico12','Fierro12','generico13@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('15','Generico13','Fierro13','generico14@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('16','Generico14','Fierro14','generico15@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('17','Generico15','Fierro15','generico16@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('18','Generico16','Fierro16','generico17@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('19','Generico17','Fierro17','generico18@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('20','Generico18','Fierro18','generico19@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('21','Generico19','Fierro19','generico20@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('22','Generico20','Fierro20','generico21@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('23','Generico21','Fierro21','generico22@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('24','Generico22','Fierro22','generico23@wedev.cl','2018-03-15','');
INSERT INTO clients (id,name,lastname,email,created_at,photo) VALUES('25','Generico23','Fierro23','generico24@wedev.cl','2018-03-15','');

INSERT INTO products (name, price, created_at) VALUES('Panasonic Pantalla LCD', 259990, NOW());
INSERT INTO products (name, price, created_at) VALUES('Sony Camara digital DSC-W320B', 123490, NOW());
INSERT INTO products (name, price, created_at) VALUES('Apple iPod shuffle', 1499990, NOW());
INSERT INTO products (name, price, created_at) VALUES('Sony Notebook Z110', 37990, NOW());
INSERT INTO products (name, price, created_at) VALUES('Hewlett Packard Multifuncional F2280', 69990, NOW());
INSERT INTO products (name, price, created_at) VALUES('Bianchi Bicicleta Aro 26', 69990, NOW());
INSERT INTO products (name, price, created_at) VALUES('Mica Comoda 5 Cajones', 299990, NOW());

INSERT INTO bills (description, observation, client_id, created_at) VALUES('Factura equipos de oficina', null, 1, NOW());
INSERT INTO items_bills (quantity, bill_id, product_id) VALUES(1, 1, 1);
INSERT INTO items_bills (quantity, bill_id, product_id) VALUES(2, 1, 4);
INSERT INTO items_bills (quantity, bill_id, product_id) VALUES(1, 1, 5);
INSERT INTO items_bills (quantity, bill_id, product_id) VALUES(1, 1, 7);

INSERT INTO bills (description, observation, client_id, created_at) VALUES('Factura Bicicleta', 'Alguna nota importante!', 1, NOW());
INSERT INTO items_bills (quantity, bill_id, product_id) VALUES(3, 2, 6);